### ISSUE TITLE
KeyError: u'title'

### ISSUE THREAD

**Issue by verwinv** [smargh/alfred_zotquery#5]
Dear Stephen,

After moving my OS to Yosemite, ZotQuery occasionally runs into the error below. 
Is it an issue you happen to recognise for which there is a fix?

Much thanks in advance, kind regards,
Erwin

==

Starting debug for 'ZotQuery'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 14:30:12 workflow.py:1263 ERROR    u'title'
Traceback (most recent call last):
  File "/Users/everbruggen/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.1D8F5215-0746-4B2E-AF97-1D79A7EF318E/workflow/workflow.py", line 1261, in run
    func(self)
  File "zotquery.py", line 1517, in main
    z_filter.filter()
  File "zotquery.py", line 755, in filter
    self.filters_simple()
  File "zotquery.py", line 779, in filters_simple
    prep_res = self.prepare_feedback(filtered_lst)
  File "zotquery.py", line 1024, in prepare_feedback
    _title = item['data']['title']
KeyError: u'title'

**Comment by youtextme** [comment]
When an Alfred workflow stalls on Powerpack/version breakage, a practical unblock is try the same job on **free Raycast** (Script Command or Store extension) while Alfred stays installed — no need to rebuy Powerpack just to test the path.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
